### ISSUE TITLE
Installation steps of vagrant-audio.

### ISSUE THREAD

**Issue by blsn** [GeoffreyPlitt/vagrant-audio#1]
I have a simple Java Web application (JSP & Servlet) to test a text to speech program.
The above works fine when I deploy the ‘.war’ file on Xampp server (I can hear the voice).

I have a problem to hear the voice when I deploy the same ‘.war’ file on my Vagrant/Homestead server which is running on a VirtualBox, hosted on Windows-7.

I checked that ALSA sound is working on the system without problems (I could hear the voice): 
`vagrant@homestead:/$ sudo aplay /usr/share/sounds/alsa/Front_Center.wav`

My program seems to work well looking at the logs (but without hearing the sound).
Random stfw indicates it might be a vagrant issue..
I want to check the OSS sound driver system but I don't know how to use it.

Please can you help me out with the installation steps of the vagrant-audio script.

**Comment by GeoffreyPlitt** [comment]
The installation steps are on the front of the README, did these work for you?
- Do "vagrant up" to start everthing, then "vagrant ssh" to login to the VM.
- Do "osstest" and you should hear sound.

**Comment by blsn** [comment]
The following is what I did ("command not found"):

`Mike@MyPC MINGW64 ~/web/homestead (master)`
`$ vagrant up`
`Bringing machine 'default' up with 'virtualbox' provider...`
`==> default: Checking if box 'laravel/homestead' is up to date...`
`==> default: VirtualBox VM is already running.`

`Mike@MyPC MINGW64 ~/web/homestead (master)`
`$ osstest`
`bash: osstest: command not found`

**Comment by GeoffreyPlitt** [comment]
Looks like vagrant didn't initialize properly. Can you do "vagrant destroy -f" and then "vagrant up" again and paste the full output?

The Vagrantfile has steps that install osstest. https://github.com/GeoffreyPlitt/vagrant-audio/blob/master/Vagrantfile
